shared_buffers = '256MB'
effective_cache_size = '768MB'
work_mem = '2MB'
maintenance_work_mem = '64MB'
autovacuum_work_mem = '32MB'
max_connections = 20
max_parallel_workers_per_gather = 0
max_parallel_maintenance_workers = 0
max_wal_size = '512MB'
min_wal_size = '80MB'
temp_file_limit = '256MB'
statement_timeout = '8s'
lock_timeout = '1s'
idle_in_transaction_session_timeout = '10s'
log_min_duration_statement = 1000
logging_collector = on
log_directory = 'log'
log_filename = 'probes-%a.log'
log_rotation_age = '1d'
log_rotation_size = '16MB'
log_truncate_on_rotation = on
autovacuum_vacuum_scale_factor = 0.03
autovacuum_analyze_scale_factor = 0.02
autovacuum_max_workers = 2
