global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/hyperspace-alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 127.0.0.1:9093

scrape_configs:
  - job_name: hyperspace-control-plane-api
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets:
          - control-plane.hyperspace.zone
        labels:
          cluster: mainnet
          role: control-plane-api

  - job_name: hyperspace-control-plane-worker
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
          - 5.199.161.13:9091
        labels:
          cluster: mainnet
          role: control-plane-worker

  - job_name: hyperspace-gate-node
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ["103.57.248.66:9100"]
        labels:
          cluster: mainnet
          role: gate
          gate: gate-ap-hkg-21
          probe_host: gate-ap-hkg-21.hyperspace.zone
          public_ipv4: 103.57.248.66
      - targets: ["5.199.166.24:9100"]
        labels:
          cluster: mainnet
          role: gate
          gate: gate-ap-sin-21
          probe_host: gate-ap-sin-21.hyperspace.zone
          public_ipv4: 5.199.166.24
      - targets: ["88.216.188.7:9100"]
        labels:
          cluster: mainnet
          role: gate
          gate: gate-ap-tyo-21
          probe_host: gate-ap-tyo-21.hyperspace.zone
          public_ipv4: 88.216.188.7
      - targets: ["84.32.231.46:9100"]
        labels:
          cluster: mainnet
          role: gate
          gate: gate-eu-ams-21
          probe_host: gate-eu-ams-21.hyperspace.zone
          public_ipv4: 84.32.231.46
      - targets: ["84.32.59.174:9100"]
        labels:
          cluster: mainnet
          role: gate
          gate: gate-eu-fra-21
          probe_host: gate-eu-fra-21.hyperspace.zone
          public_ipv4: 84.32.59.174
      - targets: ["94.237.56.185:9100"]
        labels:
          cluster: mainnet
          role: gate
          gate: gate-eu-lon-01
          probe_host: gate-eu-lon-01.hyperspace.zone
          public_ipv4: 94.237.56.185
      - targets: ["194.62.98.129:9100"]
        labels:
          cluster: mainnet
          role: gate
          gate: gate-eu-mad-01
          probe_host: gate-eu-mad-01.hyperspace.zone
          public_ipv4: 194.62.98.129
      - targets: ["91.190.155.145:9100"]
        labels:
          cluster: mainnet
          role: gate
          gate: gate-eu-osl-01
          probe_host: gate-eu-osl-01.hyperspace.zone
          public_ipv4: 91.190.155.145
      - targets: ["5.199.174.131:9100"]
        labels:
          cluster: mainnet
          role: gate
          gate: gate-eu-sia-21
          probe_host: gate-eu-sia-21.hyperspace.zone
          public_ipv4: 5.199.174.131
      - targets: ["84.32.99.242:9100"]
        labels:
          cluster: mainnet
          role: gate
          gate: gate-eu-sto-21
          probe_host: gate-eu-sto-21.hyperspace.zone
          public_ipv4: 84.32.99.242
      - targets: ["88.216.68.89:9100"]
        labels:
          cluster: mainnet
          role: gate
          gate: gate-na-chi-21
          probe_host: gate-na-chi-21.hyperspace.zone
          public_ipv4: 88.216.68.89
      - targets: ["95.111.215.105:9100"]
        labels:
          cluster: mainnet
          role: gate
          gate: gate-na-sjc-01
          probe_host: gate-na-sjc-01.hyperspace.zone
          public_ipv4: 95.111.215.105
      - targets: ["172.245.235.216:9100"]
        labels:
          cluster: mainnet
          role: gate
          gate: gate-na-slc-21
          probe_host: gate-na-slc-21.hyperspace.zone
          public_ipv4: 172.245.235.216
      - targets: ["109.104.155.28:9100"]
        labels:
          cluster: mainnet
          role: gate
          gate: gate-sa-sao-21
          probe_host: gate-sa-sao-21.hyperspace.zone
          public_ipv4: 109.104.155.28
