[Journal]
Storage=persistent
SystemMaxUse=200M
SystemKeepFree=1G
SystemMaxFileSize=32M
RuntimeMaxUse=16M
RuntimeKeepFree=32M
RuntimeMaxFileSize=4M
MaxRetentionSec=7day
RateLimitIntervalSec=30s
RateLimitBurst=5000
ForwardToSyslog=no
