[Journal]
Storage=persistent
SystemMaxUse=256M
SystemKeepFree=2G
SystemMaxFileSize=32M
RuntimeMaxUse=32M
RuntimeKeepFree=64M
RuntimeMaxFileSize=8M
MaxRetentionSec=7day
RateLimitIntervalSec=30s
RateLimitBurst=10000
ForwardToSyslog=no
