import {
  publicArtifactDownloadResponseSchema,
  publicArtifactDownloadTokenResponseSchema,
  publicAuthResponseSchema,
  publicBillingSummaryResponseSchema,
  publicAuthMeResponseSchema,
  publicCreateSessionRequestSchema,
  publicGateBenchmarkMatrixResponseSchema,
  publicGatesResponseSchema,
  publicGoogleOAuthStartResponseSchema,
  publicLoginRequestSchema,
  publicNetworkMeResponseSchema,
  publicRawWireGuardConfigResponseSchema,
  publicRegisterRequestSchema,
  publicRequestEmailLoginCodeRequestSchema,
  publicRequestEmailLoginCodeResponseSchema,
  publicSessionResponseSchema,
  publicSessionsResponseSchema,
  publicVerifyEmailLoginCodeRequestSchema,
} from "../api/public.js";

export const publicApiSchemas = {
  registerRequest: publicRegisterRequestSchema,
  loginRequest: publicLoginRequestSchema,
  requestEmailLoginCodeRequest: publicRequestEmailLoginCodeRequestSchema,
  requestEmailLoginCodeResponse: publicRequestEmailLoginCodeResponseSchema,
  verifyEmailLoginCodeRequest: publicVerifyEmailLoginCodeRequestSchema,
  googleOAuthStartResponse: publicGoogleOAuthStartResponseSchema,
  authResponse: publicAuthResponseSchema,
  authMeResponse: publicAuthMeResponseSchema,
  billingSummaryResponse: publicBillingSummaryResponseSchema,
  createSessionRequest: publicCreateSessionRequestSchema,
  sessionResponse: publicSessionResponseSchema,
  sessionsResponse: publicSessionsResponseSchema,
  gatesResponse: publicGatesResponseSchema,
  gateBenchmarkMatrixResponse: publicGateBenchmarkMatrixResponseSchema,
  networkMeResponse: publicNetworkMeResponseSchema,
  artifactDownloadTokenResponse: publicArtifactDownloadTokenResponseSchema,
  artifactDownloadResponse: publicArtifactDownloadResponseSchema,
  rawWireGuardConfigResponse: publicRawWireGuardConfigResponseSchema
} as const;
