import {
  publicArtifactDownloadResponseSchema,
  publicArtifactDownloadTokenResponseSchema,
  publicAuthResponseSchema,
  publicBillingSummaryResponseSchema,
  publicAuthMeResponseSchema,
  publicCreateSolanaWalletChallengeRequestSchema,
  publicCreateSessionRequestSchema,
  publicCreateTopupRequestSchema,
  publicGateBenchmarkMatrixResponseSchema,
  publicGatesResponseSchema,
  publicGoogleOAuthStartResponseSchema,
  publicLinkSolanaWalletRequestSchema,
  publicLinkSolanaWalletResponseSchema,
  publicLoginRequestSchema,
  publicNetworkMeResponseSchema,
  publicRawWireGuardConfigResponseSchema,
  publicRegisterRequestSchema,
  publicRequestEmailLoginCodeRequestSchema,
  publicRequestEmailLoginCodeResponseSchema,
  publicSessionResponseSchema,
  publicSessionsResponseSchema,
  publicSolanaWalletChallengeResponseSchema,
  publicSubmitTopupRequestSchema,
  publicTopupIntentResponseSchema,
  publicVerifyEmailLoginCodeRequestSchema,
  publicWalletLinksResponseSchema
} from "../api/public.js";

export const publicApiSchemas = {
  registerRequest: publicRegisterRequestSchema,
  loginRequest: publicLoginRequestSchema,
  requestEmailLoginCodeRequest: publicRequestEmailLoginCodeRequestSchema,
  requestEmailLoginCodeResponse: publicRequestEmailLoginCodeResponseSchema,
  verifyEmailLoginCodeRequest: publicVerifyEmailLoginCodeRequestSchema,
  googleOAuthStartResponse: publicGoogleOAuthStartResponseSchema,
  authResponse: publicAuthResponseSchema,
  authMeResponse: publicAuthMeResponseSchema,
  walletLinksResponse: publicWalletLinksResponseSchema,
  createSolanaWalletChallengeRequest: publicCreateSolanaWalletChallengeRequestSchema,
  solanaWalletChallengeResponse: publicSolanaWalletChallengeResponseSchema,
  linkSolanaWalletRequest: publicLinkSolanaWalletRequestSchema,
  linkSolanaWalletResponse: publicLinkSolanaWalletResponseSchema,
  billingSummaryResponse: publicBillingSummaryResponseSchema,
  createTopupRequest: publicCreateTopupRequestSchema,
  topupIntentResponse: publicTopupIntentResponseSchema,
  submitTopupRequest: publicSubmitTopupRequestSchema,
  createSessionRequest: publicCreateSessionRequestSchema,
  sessionResponse: publicSessionResponseSchema,
  sessionsResponse: publicSessionsResponseSchema,
  gatesResponse: publicGatesResponseSchema,
  gateBenchmarkMatrixResponse: publicGateBenchmarkMatrixResponseSchema,
  networkMeResponse: publicNetworkMeResponseSchema,
  artifactDownloadTokenResponse: publicArtifactDownloadTokenResponseSchema,
  artifactDownloadResponse: publicArtifactDownloadResponseSchema,
  rawWireGuardConfigResponse: publicRawWireGuardConfigResponseSchema
} as const;
